[package]
name = "adventurers"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
adventurers_quest = { path = "../adventurers_quest" }
termgame = "^1.2.0"
serde = "1.0"
anyhow = "1.0"
ron = "0.8"
